/**
 * Writes public/sw.js after a build.
 *
 * Offline has to mean *every* room, not just the ones you happened to open
 * before the signal went. That means the precache list has to name the real
 * hashed chunks Next just produced, so this runs as a postbuild step and reads
 * them out of .next rather than guessing.
 *
 * Run by `pnpm build` via the postbuild lifecycle script.
 */

import { readFileSync, writeFileSync, readdirSync, statSync, existsSync } from "node:fs";
import { join, relative } from "node:path";

const ROOT = process.cwd();
const NEXT = join(ROOT, ".next");

/** Every route the app renders, from Next's own prerender manifest. */
function routes() {
  const p = join(NEXT, "prerender-manifest.json");
  const found = new Set(["/"]);
  if (existsSync(p)) {
    const m = JSON.parse(readFileSync(p, "utf8"));
    for (const r of Object.keys(m.routes ?? {})) {
      // icons and the manifest are assets, not pages
      if (r.startsWith("/pwa-icon") || r === "/manifest.webmanifest") continue;
      if (r === "/icon" || r === "/apple-icon") continue;
      found.add(r);
    }
  }
  return [...found].sort();
}

/** Hashed build assets. These are immutable, so they can be cached forever. */
function staticAssets() {
  const base = join(NEXT, "static");
  const out = [];
  if (!existsSync(base)) return out;
  const walk = (dir) => {
    for (const name of readdirSync(dir)) {
      const full = join(dir, name);
      if (statSync(full).isDirectory()) walk(full);
      else {
        const rel = relative(base, full).split("\\").join("/");
        // source maps are dead weight in a cache
        if (rel.endsWith(".map")) continue;
        out.push("/_next/static/" + rel);
      }
    }
  };
  walk(base);
  return out;
}

const PAGES = routes();
const ASSETS = staticAssets();
const ICONS = ["/pwa-icon/192", "/pwa-icon/512", "/pwa-icon/512-maskable", "/manifest.webmanifest"];

// a new build must not serve yesterday's chunks
const VERSION = JSON.parse(readFileSync(join(ROOT, "package.json"), "utf8")).version ?? "0";
const STAMP = `${VERSION}-${Date.now().toString(36)}`;

const sw = `/* Generated by scripts/build-sw.mjs. Do not edit by hand. */
const CACHE = "pherk-pleam-${STAMP}";

/** Everything needed to open any room with no network at all. */
const PRECACHE = ${JSON.stringify([...PAGES, ...ICONS, ...ASSETS], null, 2)};

self.addEventListener("install", (e) => {
  e.waitUntil(
    (async () => {
      const c = await caches.open(CACHE);
      // one bad URL must not fail the whole install, so they go in one at a time
      await Promise.all(
        PRECACHE.map((u) => c.add(new Request(u, { cache: "reload" })).catch(() => {})),
      );
      await self.skipWaiting();
    })(),
  );
});

self.addEventListener("activate", (e) => {
  e.waitUntil(
    (async () => {
      const keys = await caches.keys();
      await Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)));
      await self.clients.claim();
    })(),
  );
});

self.addEventListener("message", (e) => {
  if (e.data === "skip-waiting") self.skipWaiting();
});

const isStatic = (u) => u.pathname.startsWith("/_next/static/");
const isFont = (u) =>
  u.hostname === "fonts.googleapis.com" || u.hostname === "fonts.gstatic.com";

self.addEventListener("fetch", (e) => {
  const req = e.request;
  if (req.method !== "GET") return;

  const url = new URL(req.url);

  // Hashed build output and fonts never change under the same URL.
  if (isStatic(url) || isFont(url)) {
    e.respondWith(
      (async () => {
        const hit = await caches.match(req);
        if (hit) return hit;
        try {
          const res = await fetch(req);
          if (res.ok || res.type === "opaque") {
            const c = await caches.open(CACHE);
            c.put(req, res.clone());
          }
          return res;
        } catch {
          return hit ?? Response.error();
        }
      })(),
    );
    return;
  }

  // Pages: fresh when there is signal, cached when there is not.
  if (req.mode === "navigate") {
    e.respondWith(
      (async () => {
        try {
          const res = await fetch(req);
          const c = await caches.open(CACHE);
          c.put(req, res.clone());
          return res;
        } catch {
          return (
            (await caches.match(req)) ??
            (await caches.match(url.pathname)) ??
            (await caches.match("/")) ??
            Response.error()
          );
        }
      })(),
    );
    return;
  }

  // Everything else: cache first, then network, and remember what came back.
  e.respondWith(
    (async () => {
      const hit = await caches.match(req);
      if (hit) return hit;
      try {
        const res = await fetch(req);
        if (res.ok) {
          const c = await caches.open(CACHE);
          c.put(req, res.clone());
        }
        return res;
      } catch {
        return Response.error();
      }
    })(),
  );
});
`;

writeFileSync(join(ROOT, "public", "sw.js"), sw);
console.log(
  `sw.js written: ${PAGES.length} pages, ${ASSETS.length} build assets, cache ${STAMP}`,
);
